// Generated by LiveScript 1.6.0
(function(){
  var react, icons, getPrimaryInfo, getLang, navigate;
  react = require('react');
  icons = require('../icons.js');
  getPrimaryInfo = require('../get-primary-info.js');
  getLang = require('../get-lang.js');
  navigate = require('../navigate.js');
  module.exports = function(store, web3t){
    var lang, style, showClass, show, buttonAdd, children;
    lang = getLang(store);
    style = getPrimaryInfo(store);
    showClass = store.menu.show ? 'show' : "";
    show = function(){
      return store.menu.show = !store.menu.show;
    };
    buttonAdd = {
      color: style.app.text,
      background: style.app.bgBtn,
      filter: style.app.icon1
    };
    return react.createElement('button', {
      style: buttonAdd,
      onClick: show,
      className: showClass + " button burger burger943922841"
    }, children = react.createElement('img', {
      src: icons.menu + "",
      className: 'icon-svg-plus'
    }));
  };
}).call(this);
