// Generated by LiveScript 1.6.0
(function(){
  var react, getPrimaryInfo, CopyToClipboard, copiedInform, copy;
  react = require('react');
  getPrimaryInfo = require('../get-primary-info.ls');
  CopyToClipboard = require('react-copy-to-clipboard').CopyToClipboard;
  copiedInform = require('../copied-inform.ls');
  copy = require('../copy.ls');
  module.exports = function(arg$){
    var store, text, style, filterIcon, icon2, enter, leave, children;
    store = arg$.store, text = arg$.text;
    style = getPrimaryInfo(store);
    filterIcon = {
      filter: style.app.filterIcon
    };
    icon2 = {
      filter: style.app.icon2
    };
    enter = function(){
      return store.current.tryCopy = text;
    };
    leave = function(){
      return store.current.tryCopy = null;
    };
    return react.createElement(CopyToClipboard, {
      text: text + "",
      onCopy: copiedInform(store),
      style: icon2,
      onMouseEnter: enter,
      onMouseLeave: leave
    }, children = copy(store));
  };
}).call(this);
