// Generated by LiveScript 1.6.0
(function(){
  var react, menuFuncs, naming, getPrimaryInfo, getLang, icon, navigate, switchAccount, namingPart, manageAccount;
  react = require('react');
  menuFuncs = require('../menu-funcs.ls');
  naming = require('./naming.ls');
  getPrimaryInfo = require('../get-primary-info.ls');
  getLang = require('../get-lang.ls');
  icon = require('./icon.ls');
  navigate = require('../navigate.ls');
  switchAccount = function(store, web3t){
    var ref$, accountLeft, accountRight, changeAccountIndex, style, inputStyle, color, buttonPrimary2Style, children;
    ref$ = menuFuncs(store, web3t), accountLeft = ref$.accountLeft, accountRight = ref$.accountRight, changeAccountIndex = ref$.changeAccountIndex;
    style = getPrimaryInfo(store);
    inputStyle = {
      background: style.app.wallet,
      color: style.app.text,
      border: "0"
    };
    color = {
      color: style.app.text
    };
    buttonPrimary2Style = {
      border: "1px solid " + style.app.wallet,
      color: style.app.text,
      background: style.app.primary2,
      backgroundColor: style.app.primary2Spare
    };
    return react.createElement('div', {
      style: color,
      className: 'switch-account'
    }, children = [
      react.createElement('div', {
        className: 'mb-12'
      }, ' Account Index:'), react.createElement('span', {
        onClick: accountLeft,
        style: buttonPrimary2Style,
        className: 'button left'
      }, children = icon('ChevronLeft', 15)), react.createElement('span', {
        className: 'bold'
      }, children = react.createElement('input', {
        value: store.current.accountIndex + "",
        style: inputStyle,
        onChange: changeAccountIndex,
        className: 'change-index'
      })), react.createElement('span', {
        onClick: accountRight,
        style: buttonPrimary2Style,
        className: 'button right'
      }, children = icon('ChevronRight', 15))
    ]);
  };
  namingPart = function(arg$){
    var store, web3t, children;
    store = arg$.store, web3t = arg$.web3t;
    return react.createElement('div', {
      className: 'section'
    }, children = [
      react.createElement('div', {
        className: 'title'
      }, ' ' + lang.yourNickname), react.createElement('div', {
        className: 'description'
      }, ' ' + lang.yourNicknameInfo), react.createElement('div', {
        className: 'content'
      }, children = naming({
        store: store,
        web3t: web3t
      }))
    ]);
  };
  manageAccount = function(store, web3t){
    var ref$, current, generate, enterPin, cancelTry, editSeed, saveSeed, changeSeed, exportPrivateKey, style, lang, inputStyle, color, logoStyle, buttonPrimary2Style, buttonPrimary3Style, gotoTerms, gotoPrivacy, children;
    ref$ = menuFuncs(store, web3t), current = ref$.current, generate = ref$.generate, enterPin = ref$.enterPin, cancelTry = ref$.cancelTry, editSeed = ref$.editSeed, saveSeed = ref$.saveSeed, changeSeed = ref$.changeSeed, exportPrivateKey = ref$.exportPrivateKey;
    style = getPrimaryInfo(store);
    lang = getLang(store);
    inputStyle = {
      background: style.app.wallet,
      color: style.app.text
    };
    color = {
      color: style.app.text
    };
    logoStyle = {
      filter: style.app.filterLogo
    };
    buttonPrimary2Style = {
      border: "1px solid " + style.app.primary2,
      color: style.app.text,
      background: style.app.primary2,
      backgroundColor: style.app.primary2Spare
    };
    buttonPrimary3Style = {
      border: "1px solid " + style.app.border,
      color: style.app.text2,
      background: style.app.primary3,
      backgroundColor: style.app.primary3Spare
    };
    gotoTerms = function(){
      return navigate(store, web3t, 'terms2');
    };
    gotoPrivacy = function(){
      return navigate(store, web3t, 'privacy');
    };
    return react.createElement('div', {}, children = [
      react.createElement('div', {
        className: 'section'
      }, children = [
        react.createElement('div', {
          className: 'logo'
        }, children = react.createElement('img', {
          src: style.branding.logo + "",
          style: logoStyle
        })), react.createElement('div', {
          style: color,
          className: 'title'
        }, children = [
          react.createElement('span', {}, ' Velas Wallet'), react.createElement('span', {
            className: 'bold low'
          }, ' ' + store.version)
        ]), react.createElement('div', {
          style: color,
          className: 'description pb-0'
        }, children = [
          react.createElement('span', {}, ' ' + lang.aboutWallet + '.'), react.createElement('br', {}), react.createElement('span', {}, ' ' + lang.plsRead), react.createElement('span', {
            onClick: gotoPrivacy,
            className: 'link'
          }, ' ' + lang.privacyPolicy), react.createElement('span', {}, '  &'), react.createElement('span', {
            onClick: gotoTerms,
            className: 'link'
          }, ' ' + lang.termsOfUse)
        ])
      ]), react.createElement('div', {
        className: 'section'
      }, children = [
        react.createElement('div', {
          style: color,
          className: 'title'
        }, ' ' + lang.switchAccountIndex), react.createElement('div', {
          style: color,
          className: 'description'
        }, children = [
          react.createElement('span', {
            className: 'bold'
          }, ' ' + lang.forAdvancedUsers + '.'), react.createElement('span', {}, ' ' + lang.switchAccountInfo)
        ]), react.createElement('div', {
          className: 'content'
        }, children = switchAccount(store, web3t))
      ]), react.createElement('div', {
        className: 'section last'
      }, children = [
        react.createElement('div', {
          style: color,
          className: 'title'
        }, ' ' + lang.exportPrivateKey), react.createElement('div', {
          style: color,
          className: 'description'
        }, children = [
          react.createElement('span', {
            className: 'bold'
          }, ' ' + lang.forAdvancedUsers), react.createElement('span', {}, ' ' + lang.exportPrivateKeyWarning + '.')
        ]), react.createElement('div', {
          className: 'content'
        }, children = react.createElement('button', {
          onClick: exportPrivateKey,
          style: buttonPrimary2Style
        }, ' ' + lang.showSecret))
      ])
    ]);
  };
  module.exports = function(arg$){
    var store, web3t, closeAccount, style, accountBodyStyle, borderStyle, lang, children;
    store = arg$.store, web3t = arg$.web3t;
    if (store.current.manageAccount !== true) {
      return null;
    }
    closeAccount = menuFuncs(store, web3t).closeAccount;
    style = getPrimaryInfo(store);
    accountBodyStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    borderStyle = {
      background: style.app.header,
      color: style.app.text
    };
    lang = getLang(store);
    return react.createElement('div', {
      className: 'manage-account manage-account-1411573454'
    }, children = react.createElement('div', {
      style: accountBodyStyle,
      className: 'account-body'
    }, children = [
      react.createElement('div', {
        style: borderStyle,
        className: 'title'
      }, children = [
        react.createElement('div', {
          className: 'header'
        }, ' ' + lang.manageAccount), react.createElement('div', {
          onClick: closeAccount,
          className: 'close'
        }, children = icon('X', 20))
      ]), react.createElement('div', {
        className: 'settings'
      }, children = manageAccount(store, web3t))
    ]));
  };
}).call(this);
