// Generated by LiveScript 1.6.0
(function(){
  var ref$, objToPairs, pairsToObj, map, toJS, getKeys, web3, slice$ = [].slice;
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, pairsToObj = ref$.pairsToObj, map = ref$.map;
  toJS = require('mobx').toJS;
  getKeys = require('./api.ls').getKeys;
  web3 = require('./web3.ls');
  module.exports = function(store, mnemonic, cb){
    var generateCoinWallet, generateCoinWallets;
    mnemonic == null && (mnemonic = "");
    generateCoinWallet = function(coin, cb){
      var network, index;
      network = coin[store.current.network];
      if (network == null || (network != null ? network.disabled : void 8) === true) {
        return cb(null);
      }
      index = store.current.accountIndex;
      return getKeys({
        index: index,
        network: network,
        mnemonic: mnemonic,
        token: coin.token
      }, function(err, wallet){
        var balance, balanceUsd, usdRate, marketHistoryPrices;
        if (err != null) {
          return cb(err);
        }
        balance = '...';
        balanceUsd = '...';
        usdRate = '...';
        marketHistoryPrices = null;
        wallet.coin = coin;
        wallet.network = network;
        wallet.balance = balance;
        wallet.balanceUsd = balanceUsd;
        wallet.usdRate = usdRate;
        wallet.mnemonic = mnemonic;
        wallet.marketHistoryPrices = marketHistoryPrices;
        return cb(null, wallet);
      });
    };
    generateCoinWallets = function(arg$, cb){
      var coin, rest;
      coin = arg$[0], rest = slice$.call(arg$, 1);
      if (coin == null) {
        return cb(null, []);
      }
      return generateCoinWallet(coin, function(err, walletOrNull){
        if (walletOrNull != null) {
          coin.wallet = walletOrNull;
          walletOrNull.usdRate = '..';
          walletOrNull.eurRate = '..';
          walletOrNull.balanceUsd = '..';
          walletOrNull.pendingSent = '..';
          walletOrNull.balance = '..';
          walletOrNull.txsStatus = 'not-loaded';
          walletOrNull.status = 'loading';
          walletOrNull.state = '';
        }
        return generateCoinWallets(rest, function(err, wallets){
          var currentWallets, all;
          if (err != null) {
            console.log(err);
          }
          currentWallets = (function(){
            switch (false) {
            case walletOrNull == null:
              return [walletOrNull];
            default:
              return [];
            }
          }());
          if (err != null) {
            return cb(null, currentWallets);
          }
          all = currentWallets.concat(wallets);
          return cb(null, all);
        });
      });
    };
    return generateCoinWallets(store.coins, function(err, wallets){
      if (err != null) {
        return cb(err);
      }
      return cb(null, {
        mnemonic: mnemonic,
        wallets: wallets
      });
    });
  };
}).call(this);
