// Generated by LiveScript 1.6.0
(function(){
  var react, navigate, getPrimaryInfo, web3, getLang, historyFuncs, icons, button, get, terms;
  react = require('react');
  navigate = require('../navigate.ls');
  getPrimaryInfo = require('../get-primary-info.ls');
  web3 = require('../web3.ls');
  getLang = require('../get-lang.ls');
  historyFuncs = require('../history-funcs.ls');
  icons = require('../icons.ls');
  button = require('../components/button.ls');
  get = require('../../web3t/providers/superagent.js').get;
  terms = function(arg$){
    var store, web3t, lang, goBack, info, style, buttonStyle, btnIcon, accept, children;
    store = arg$.store, web3t = arg$.web3t;
    lang = getLang(store);
    goBack = function(){
      return navigate(store, web3t, 'settings');
    };
    info = getPrimaryInfo(store);
    style = {
      background: info.app.wallet,
      color: info.app.text
    };
    buttonStyle = {
      color: info.app.text
    };
    btnIcon = {
      filter: info.app.btnIcon
    };
    accept = function(){
      navigate(store, web3t, ':init');
      return web3t.refresh(function(){});
    };
    return react.createElement('div', {
      className: 'terms terms1061065338'
    }, children = react.createElement('div', {
      className: 'terms-body'
    }, children = [
      react.createElement('div', {
        className: 'header'
      }, ' ' + lang.privacyPolicy), react.createElement('textarea', {
        value: store.terms + "",
        style: style
      }), react.createElement('div', {
        className: 'buttons'
      }, children = button({
        store: store,
        text: 'back',
        onClick: goBack,
        icon: 'arrowLeft',
        type: 'primary'
      }))
    ]));
  };
  terms.init = function(arg$, cb){
    var store, privacy;
    store = arg$.store;
    privacy = "Velas Wallet Privacy Notice\nLast updated: July 2, 2020\nThe Velas Wallet available at https://wallet.velas.com/, including its browser extension (plugin), desktop or mobile application (the “Velas Wallet”) is operated by Velas Network AG (“Velas”, “we”, “us”).\nThe terms “you” and “your” are used to refer to you as a user of the Velas Wallet, including you as a holder of a digital wallet on the Velas Wallet and/or any person authorised to use your Wallet.\n“Personal data” or “personal information” means information that relates to an identified or identifiable individual.\n    •  NO PERSONAL DATA PROCESSED\nVelas informs you that we do not collect, process, or store any personal information. Moreover, you do not have an opportunity to provide your personal data to us through the Velas Wallet.\nVelas is not able and will not identify you as an individual.\nYour PIN-code, private key, and mnemonic phrase are encrypted and processed locally on your device and are not processed on our servers.\n    •  SECURITY OF YOUR PERSONAL DATA\nSince Velas does not process your personal data, you are solely responsible for maintaining the confidentiality of your personal information.\n    •  CONTACT DETAILS\nShould you have any questions regarding this Privacy Notice, please contact us at:\nVelas Network AG\nDammstrasse 16,\nZug 6300, Switzerland\nEmail: info@velas.com.\n    •  CHANGES TO THIS PRIVACY NOTICE\nVelas may unilaterally make changes to this Privacy Notice. In such case, we will update the “Last updated” date above. Such changes will take effect as soon as they are posed unless otherwise is decided by Velas. Please check back frequently to see any updates or changes to this Privacy Notice.";
    store.terms = privacy;
    return cb(null);
  };
  module.exports = terms;
}).call(this);
