// Generated by LiveScript 1.6.0
(function(){
  var react, getPrimaryInfo, getLang, icon, icons, textField, button, round5edit, amountField, ref$, find, map, minus, div, plus, times, alertModal, notificationModal, confirmationModal, promptModal, promptModal2, promptModal3, data, promptChooseTokenModal, promptPasswordModal, confirmationControl, state, confirm, notify, prompt, prompt2, prompt3, promptPassword, promptChooseToken, alert, toString$ = {}.toString, out$ = typeof exports != 'undefined' && exports || this;
  react = require('react');
  getPrimaryInfo = require('../get-primary-info.js');
  getLang = require('../get-lang.js');
  icon = require('./icon.js');
  icons = require('../icons.js');
  textField = require('../components/text-field.js');
  button = require('../components/button.js');
  round5edit = require('../round5edit.js');
  amountField = require('../components/amount-field.js');
  ref$ = require('prelude-ls'), find = ref$.find, map = ref$.map;
  ref$ = require('../math.js'), minus = ref$.minus, div = ref$.div, plus = ref$.plus, times = ref$.times;
  alertModal = function(store){
    var cancel, style, confirmationStyle, confirmationStyle2, buttonStyle, confirmation, lang, text, textRows, buildText, children;
    if (toString$.call(store.current.alert).slice(8, -1) !== 'String') {
      return null;
    }
    cancel = function(){
      var callback;
      store.current.alert = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(false);
      }
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    confirmationStyle2 = {
      color: style.app.text
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    text = store.current.alert;
    textRows = text.split("\n");
    buildText = function(txt){
      return react.createElement('div', {
        className: 'text-block'
      }, ' ' + txt);
    };
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: confirmationStyle,
        className: 'header'
      }, ' Alert'), react.createElement('div', {
        style: confirmationStyle2,
        className: 'text'
      }, ' '), map(buildText)(
      textRows), react.createElement('div', {
        className: 'buttons'
      }, children = react.createElement('button', {
        onClick: cancel,
        style: buttonStyle,
        id: "alert-close",
        className: 'button'
      }, children = react.createElement('span', {
        className: 'cancel'
      }, children = [
        react.createElement('img', {
          src: icons.close + "",
          className: 'icon-svg-cancel'
        }), " " + lang.cancel
      ])))
    ]));
  };
  notificationModal = function(store){
    var cancel, style, confirmationStyle, confirmationStyle2, buttonStyle, confirmation, lang, children;
    if (toString$.call(store.current.notification).slice(8, -1) !== 'String') {
      return null;
    }
    cancel = function(){
      var callback;
      store.current.notification = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(false);
      }
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    confirmationStyle2 = {
      color: style.app.text
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: confirmationStyle,
        className: 'header'
      }, ' Alert'), react.createElement('div', {
        style: confirmationStyle2,
        className: 'text'
      }, ' ' + store.current.notification), react.createElement('div', {
        className: 'buttons'
      }, children = react.createElement('button', {
        onClick: cancel,
        style: buttonStyle,
        id: "notification-close",
        className: 'button'
      }, children = react.createElement('span', {
        className: 'cancel'
      }, children = [
        react.createElement('img', {
          src: icons.apply + "",
          className: 'icon-svg-apply'
        }), " Ok"
      ])))
    ]));
  };
  confirmationModal = function(store){
    var confirm, cancel, style, confirmationStyle, confirmationStyle2, buttonStyle, confirmation, lang, children;
    if (toString$.call(store.current.confirmation).slice(8, -1) !== 'String') {
      return null;
    }
    confirm = function(){
      var callback;
      store.current.confirmation = true;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(true);
      }
    };
    cancel = function(){
      var callback;
      store.current.confirmation = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(false);
      }
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    confirmationStyle2 = {
      color: style.app.text
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: confirmationStyle,
        className: 'header'
      }, ' ' + lang.confirmation), react.createElement('div', {
        style: confirmationStyle2,
        className: 'text'
      }, ' ' + store.current.confirmation), react.createElement('div', {
        className: 'buttons'
      }, children = [
        react.createElement('button', {
          onClick: confirm,
          style: buttonStyle,
          id: "confirmation-confirm",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'apply'
        }, children = [
          react.createElement('img', {
            src: icons.apply + "",
            className: 'icon-svg-apply'
          }), " " + lang.confirm
        ])), react.createElement('button', {
          onClick: cancel,
          style: buttonStyle,
          id: "confirmation-close",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'cancel'
        }, children = [
          react.createElement('img', {
            src: icons.close + "",
            className: 'icon-svg-cancel'
          }), " " + lang.cancel
        ]))
      ])
    ]));
  };
  promptModal = function(store){
    var confirm, cancel, changeInput, style, confirmationStyle, inputStyle, buttonStyle, confirmation, lang, children;
    if (toString$.call(store.current.prompt).slice(8, -1) !== 'String') {
      return null;
    }
    confirm = function(){
      var callback, promptAnswer;
      store.current.prompt = true;
      callback = state.callback;
      state.callback = null;
      promptAnswer = store.current.promptAnswer;
      store.current.promptAnswer = "";
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(promptAnswer);
      }
    };
    cancel = function(){
      var callback;
      store.current.prompt = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        callback(null);
      }
      return store.current.promptAnswer = "";
    };
    changeInput = function(e){
      return store.current.promptAnswer = e.target.value;
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    inputStyle = {
      background: style.app.input,
      color: style.app.text,
      border: "0",
      textAlign: "center"
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: style = confirmationStyle,
        className: 'header'
      }, ' ' + lang.confirmation), react.createElement('div', {
        style: style = confirmationStyle,
        className: 'text'
      }, ' ' + store.current.prompt), react.createElement('div', {}, children = react.createElement('input', {
        onChange: changeInput,
        value: store.current.promptAnswer + "",
        style: inputStyle,
        id: "prompt-input"
      })), react.createElement('div', {
        className: 'buttons'
      }, children = [
        react.createElement('button', {
          onClick: confirm,
          style: buttonStyle,
          id: "prompt-confirm",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'apply'
        }, children = [
          react.createElement('img', {
            src: icons.apply + "",
            className: 'icon-svg-apply'
          }), " " + lang.confirm
        ])), react.createElement('button', {
          onClick: cancel,
          style: buttonStyle,
          id: "prompt-close",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'cancel'
        }, children = [
          react.createElement('img', {
            src: icons.close + "",
            className: 'icon-svg-cancel'
          }), " " + lang.cancel
        ]))
      ])
    ]));
  };
  promptModal2 = function(store){
    var wallet, confirm, cancel, amountChange, style, confirmationStyle, inputStyle, inputHolderStyle, buttonStyle, confirmation, lang, buttonPrimary3Style, maxAmountContainer, useMaxAmount, children;
    if (toString$.call(store.current.prompt2).slice(8, -1) !== 'String') {
      return null;
    }
    wallet = find(function(it){
      return it.coin.token === 'vlx_native';
    })(
    store.current.account.wallets);
    confirm = function(){
      var callback, promptAnswer;
      if (store.current.promptAnswer == null || store.current.promptAnswer === 0 || store.current.promptAnswer === "") {
        return;
      }
      store.current.prompt2 = true;
      callback = state.callback;
      state.callback = null;
      promptAnswer = store.current.promptAnswer;
      store.current.promptAnswer = "";
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(promptAnswer);
      }
    };
    cancel = function(){
      var callback;
      store.current.prompt2 = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        callback(null);
      }
      return store.current.promptAnswer = "";
    };
    amountChange = function(e){
      var balance, ref$, maxAmount, amount;
      balance = (ref$ = wallet != null ? wallet.balance : void 8) != null ? ref$ : 1;
      maxAmount = Math.floor(minus(balance, 1));
      amount = (function(){
        switch (false) {
        case !(e.target.value > maxAmount):
          return maxAmount;
        case !isNaN(e.target.value):
          return 0;
        default:
          return e.target.value;
        }
      }());
      return store.current.promptAnswer = amount;
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    inputStyle = {
      background: style.app.input,
      color: style.app.text,
      border: "0"
    };
    inputHolderStyle = {
      maxWidth: '250px',
      margin: 'auto'
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    buttonPrimary3Style = {
      border: "0",
      color: style.app.text2,
      background: style.app.primary3,
      backgroundColor: style.app.primary3Spare,
      cursor: "pointer"
    };
    maxAmountContainer = {
      textAlign: "left"
    };
    useMaxAmount = function(){
      store.current.promptAnswer = (function(){
        switch (false) {
        case wallet != null:
          return 0;
        default:
          return Math.floor(minus(wallet.balance, 1));
        }
      }());
    };
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: style = confirmationStyle,
        className: 'header'
      }, store.current.prompt2), react.createElement('div', {
        style: style = confirmationStyle,
        className: 'text'
      }), react.createElement('div', {
        style: inputHolderStyle
      }, children = [
        amountField({
          store: store,
          value: round5edit(store.current.promptAnswer) + "",
          onChange: amountChange,
          placeholder: typeof placeholder != 'undefined' && placeholder !== null ? placeholder : "0",
          id: typeof id != 'undefined' && id !== null ? id : "prompt-input",
          token: "vlx_native"
        }), react.createElement('div', {
          style: maxAmountContainer,
          className: 'max-amount'
        }, children = react.createElement('button', {
          onClick: useMaxAmount,
          style: buttonPrimary3Style,
          type: "button",
          id: "send-max",
          className: 'send-all'
        }, ' ' + lang.useMax))
      ]), react.createElement('div', {
        className: 'buttons'
      }, children = [
        react.createElement('button', {
          onClick: confirm,
          style: buttonStyle,
          id: "prompt-confirm",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'apply'
        }, children = [
          react.createElement('img', {
            src: icons.apply + "",
            className: 'icon-svg-apply'
          }), " " + lang.confirm
        ])), react.createElement('button', {
          onClick: cancel,
          style: buttonStyle,
          id: "prompt-close",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'cancel'
        }, children = [
          react.createElement('img', {
            src: icons.close + "",
            className: 'icon-svg-cancel'
          }), " " + lang.cancel
        ]))
      ])
    ]));
  };
  promptModal3 = function(store){
    var chosenAccount, rent, active_stake, inactive_stake, balanceRaw, min_stake, confirm, cancel, amountChange, style, confirmationStyle, inputStyle, inputHolderStyle, buttonStyle, confirmation, lang, buttonPrimary3Style, maxAmountContainer, useMaxAmount, children;
    if (toString$.call(store.current.prompt3).slice(8, -1) !== 'String') {
      return null;
    }
    console.log("prompt modal split");
    chosenAccount = store.staking.chosenAccount;
    rent = chosenAccount.rent;
    active_stake = div(chosenAccount.active_stake, Math.pow(10, 9));
    inactive_stake = div(chosenAccount.inactive_stake, Math.pow(10, 9));
    balanceRaw = div(chosenAccount.balanceRaw, Math.pow(10, 9));
    min_stake = "1";
    confirm = function(){
      var callback, promptAnswer;
      if (store.current.promptAnswer == null || +store.current.promptAnswer === 0 || store.current.promptAnswer === "") {
        return;
      }
      store.current.prompt3 = true;
      callback = state.callback;
      state.callback = null;
      promptAnswer = store.current.promptAnswer;
      store.current.promptAnswer = "";
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(promptAnswer);
      }
    };
    cancel = function(){
      var callback;
      store.current.prompt3 = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        callback(null);
      }
      return store.current.promptAnswer = "";
    };
    amountChange = function(e){
      var balance, maxAmount, amount;
      balance = div(chosenAccount.balanceRaw, Math.pow(10, 9));
      maxAmount = Math.floor(minus(balance, min_stake));
      amount = (function(){
        switch (false) {
        case !(e.target.value > maxAmount):
          return maxAmount;
        default:
          return e.target.value;
        }
      }());
      return store.current.promptAnswer = amount;
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    inputStyle = {
      background: style.app.input,
      color: style.app.text,
      border: "0"
    };
    inputHolderStyle = {
      maxWidth: '250px',
      margin: 'auto'
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    buttonPrimary3Style = {
      border: "0",
      color: style.app.text2,
      background: style.app.primary3,
      backgroundColor: style.app.primary3Spare,
      cursor: "pointer"
    };
    maxAmountContainer = {
      textAlign: "left"
    };
    useMaxAmount = function(){
      store.current.promptAnswer = (function(){
        switch (false) {
        case chosenAccount != null:
          return 0;
        default:
          return minus(minus(balanceRaw, active_stake), min_stake);
        }
      }());
    };
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: style = confirmationStyle,
        className: 'header'
      }, store.current.prompt3), react.createElement('div', {
        style: style = confirmationStyle,
        className: 'text'
      }), react.createElement('div', {
        style: inputHolderStyle
      }, children = [
        amountField({
          store: store,
          token: "vlx_native",
          value: round5edit(store.current.promptAnswer) + "",
          onChange: amountChange,
          placeholder: typeof placeholder != 'undefined' && placeholder !== null ? placeholder : "0",
          id: typeof id != 'undefined' && id !== null ? id : "prompt-input"
        }), react.createElement('div', {
          style: maxAmountContainer,
          className: 'max-amount'
        }, children = react.createElement('button', {
          onClick: useMaxAmount,
          style: buttonPrimary3Style,
          type: "button",
          id: "send-max",
          className: 'send-all'
        }, ' ' + lang.useMax))
      ]), react.createElement('div', {
        className: 'buttons'
      }, children = [
        react.createElement('button', {
          onClick: confirm,
          style: buttonStyle,
          id: "prompt-confirm",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'apply'
        }, children = [
          react.createElement('img', {
            src: icons.apply + "",
            className: 'icon-svg-apply'
          }), " " + lang.confirm
        ])), react.createElement('button', {
          onClick: cancel,
          style: buttonStyle,
          id: "prompt-close",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'cancel'
        }, children = [
          react.createElement('img', {
            src: icons.close + "",
            className: 'icon-svg-cancel'
          }), " " + lang.cancel
        ]))
      ])
    ]));
  };
  data = {
    token: null
  };
  promptChooseTokenModal = function(store){
    var text, confirm, cancel, style, confirmationStyle, inputStyle, inputHolderStyle, buttonStyle, confirmation, lang, buttonPrimary3Style, filterBody, imgStyle, optionStyle, ulStyle, textStyle, buildItem, disabledLayoutStyle, promptAnswer, ref$, displayToken, btnDisabled, onFocus, children;
    if (toString$.call(store.current.chooseToken).slice(8, -1) !== 'String') {
      return null;
    }
    text = store.current.chooseToken;
    confirm = function(){
      var callback, promptAnswer;
      onFocus();
      if (store.current.promptAnswer == null || store.current.promptAnswer === "") {
        return;
      }
      store.current.chooseToken = true;
      callback = state.callback;
      state.callback = null;
      promptAnswer = store.current.promptAnswer;
      store.current.promptAnswer = "";
      data.token = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(promptAnswer);
      }
    };
    cancel = function(){
      var callback;
      store.current.chooseToken = false;
      callback = state.callback;
      state.callback = null;
      data.token = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        callback(null);
      }
      return store.current.promptAnswer = "";
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    inputStyle = {
      background: style.app.input,
      color: style.app.text,
      border: "0"
    };
    inputHolderStyle = {
      maxWidth: '250px',
      margin: 'auto'
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    lang = getLang(store);
    buttonPrimary3Style = {
      border: "0",
      color: style.app.text2,
      background: style.app.primary3,
      backgroundColor: style.app.primary3Spare,
      cursor: "pointer"
    };
    inputStyle = {
      color: "black",
      border: "0",
      marginRight: "10px",
      height: "32px",
      textAlign: "center"
    };
    filterBody = {
      border: "1px solid " + style.app.border,
      background: style.app.header
    };
    imgStyle = {
      width: "30px",
      position: "relative",
      top: "8px"
    };
    optionStyle = {
      listStyle: "none",
      color: style.app.text,
      padding: "5px 10px",
      cursor: "pointer",
      display: "inline-block"
    };
    ulStyle = {
      padding: 0,
      textAlign: "left",
      maxWidth: "300px",
      margin: "20px auto"
    };
    textStyle = {
      padding: "5px"
    };
    buildItem = function(item){
      var ref$, image, name, token, onClick, activeClass, children;
      ref$ = item.coin, image = ref$.image, name = ref$.name, token = ref$.token;
      onClick = function(){
        store.current.promptAnswer = token;
        return data.token = name;
      };
      activeClass = store.current.promptAnswer === token ? "active" : "";
      return react.createElement('li', {
        onClick: onClick,
        style: optionStyle,
        className: activeClass + " lang-item"
      }, children = [
        react.createElement('img', {
          src: image + "",
          style: imgStyle
        }), react.createElement('span', {
          style: textStyle
        }, ' ' + name)
      ]);
    };
    inputStyle = {
      position: "relative",
      textAlign: "center",
      display: "flex"
    };
    disabledLayoutStyle = {
      zIndex: 1,
      background: "transparent",
      position: "absolute",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      width: "62%"
    };
    promptAnswer = (ref$ = store.current.promptAnswer) != null ? ref$ : null;
    displayToken = (ref$ = data.token) != null ? ref$ : "";
    btnDisabled = typeof store.current.promptAnswer !== "string" || (typeof store.current.promptAnswer === "string" && store.current.promptAnswer.length === 0);
    onFocus = function(){
      return document.querySelector('.tokeninput').focus();
    };
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: style = confirmationStyle,
        className: 'header'
      }, text), react.createElement('div', {
        style: style = confirmationStyle,
        className: 'text'
      }), react.createElement('div', {
        className: 'token-select'
      }, children = [
        react.createElement('div', {
          style: inputStyle,
          className: 'input-holder'
        }, children = [
          react.createElement('div', {
            style: disabledLayoutStyle,
            className: 'dlayout'
          }), react.createElement('input', {
            type: "text",
            value: displayToken + "",
            style: inputStyle,
            className: 'tokeninput'
          })
        ]), react.createElement('div', {
          className: 'tokens-drop'
        }, children = react.createElement('ul', {
          style: ulStyle
        }, children = map(buildItem)(
        store.current.account.wallets)))
      ]), react.createElement('div', {
        className: 'buttons'
      }, children = [
        react.createElement('button', {
          onClick: confirm,
          style: buttonStyle,
          id: "prompt-confirm",
          disabled: btnDisabled,
          className: 'button'
        }, children = react.createElement('span', {
          className: 'apply'
        }, children = [
          react.createElement('img', {
            src: icons.apply + "",
            className: 'icon-svg-apply'
          }), " " + lang.confirm
        ])), react.createElement('button', {
          onClick: cancel,
          style: buttonStyle,
          id: "prompt-close",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'cancel'
        }, children = [
          react.createElement('img', {
            src: icons.close + "",
            className: 'icon-svg-cancel'
          }), " " + lang.cancel
        ]))
      ])
    ]));
  };
  promptPasswordModal = function(store){
    var confirm, cancel, changeInput, style, confirmationStyle, inputStyle, buttonStyle, confirmation, catchKey, focusInput, lang, children;
    if (toString$.call(store.current.promptPassword).slice(8, -1) !== 'String') {
      return null;
    }
    confirm = function(){
      var callback, promptAnswer;
      store.current.promptPassword = true;
      callback = state.callback;
      state.callback = null;
      promptAnswer = store.current.promptPasswordAnswer;
      store.current.promptPasswordAnswer = "";
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        return callback(promptAnswer);
      }
    };
    cancel = function(){
      var callback;
      store.current.promptPassword = false;
      callback = state.callback;
      state.callback = null;
      if (toString$.call(callback).slice(8, -1) === 'Function') {
        callback(null);
      }
      return store.current.promptPasswordAnswer = "";
    };
    changeInput = function(e){
      return store.current.promptPasswordAnswer = e.target.value;
    };
    style = getPrimaryInfo(store);
    confirmationStyle = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text
    };
    inputStyle = {
      background: style.app.input,
      color: style.app.text,
      border: "0"
    };
    buttonStyle = {
      color: style.app.text
    };
    confirmation = {
      background: style.app.background,
      backgroundColor: style.app.bgspare,
      color: style.app.text,
      borderBottom: "1px solid " + style.app.border
    };
    catchKey = function(it){
      if (it.keyCode === 13) {
        return confirm();
      }
    };
    focusInput = function(ref){
      if (ref != null) {
        ref.focus();
      }
    };
    lang = getLang(store);
    return react.createElement('div', {
      className: 'confirmation confirmation-450558461'
    }, children = react.createElement('div', {
      style: confirmation,
      className: 'confirmation-body'
    }, children = [
      react.createElement('div', {
        style: style = confirmationStyle,
        className: 'header'
      }, ' ' + lang.confirmation), react.createElement('div', {
        style: style = confirmationStyle,
        className: 'text'
      }, ' ' + store.current.promptPassword), react.createElement('div', {
        className: 'pin-input'
      }, children = textField({
        ref: function(c){
          return {
            a: typeof a != 'undefined' && a !== null
              ? a
              : focusInput(c)
          };
        },
        store: store,
        type: 'password',
        value: store.current.promptPasswordAnswer,
        placeholder: "",
        onChange: changeInput,
        onKeyDown: catchKey,
        id: typeof id != 'undefined' && id !== null ? id : "prompt-input"
      })), react.createElement('div', {
        className: 'buttons'
      }, children = [
        react.createElement('button', {
          onClick: confirm,
          style: buttonStyle,
          id: "prompt-confirm",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'apply'
        }, children = [
          react.createElement('img', {
            src: icons.apply + "",
            className: 'icon-svg-apply'
          }), " " + lang.confirm
        ])), react.createElement('button', {
          onClick: cancel,
          style: buttonStyle,
          id: "prompt-close",
          className: 'button'
        }, children = react.createElement('span', {
          className: 'cancel'
        }, children = [
          react.createElement('img', {
            src: icons.close + "",
            className: 'icon-svg-cancel'
          }), " " + lang.cancel
        ]))
      ])
    ]));
  };
  out$.confirmationControl = confirmationControl = function(store){
    var children;
    if (store.current.pagePin != null) {
      return null;
    }
    return react.createElement('div', {}, children = [promptModal3(store), confirmationModal(store), promptModal2(store), promptModal(store), promptPasswordModal(store), alertModal(store), notificationModal(store), promptChooseTokenModal(store)]);
  };
  state = {
    callback: null
  };
  out$.confirm = confirm = function(store, text, cb){
    store.current.confirmation = text;
    return state.callback = cb;
  };
  out$.notify = notify = function(store, text, cb){
    store.current.notification = text;
    return state.callback = cb;
  };
  out$.prompt = prompt = function(store, text, cb){
    store.current.prompt = text;
    return state.callback = cb;
  };
  out$.prompt2 = prompt2 = function(store, text, cb){
    store.current.prompt2 = text;
    return state.callback = cb;
  };
  out$.prompt3 = prompt3 = function(store, text, cb){
    store.current.prompt3 = text;
    return state.callback = cb;
  };
  out$.promptPassword = promptPassword = function(store, text, cb){
    store.current.promptPassword = text;
    return state.callback = cb;
  };
  out$.promptChooseToken = promptChooseToken = function(store, text, cb){
    store.current.chooseToken = text;
    store.current.promptAnswer = '';
    return state.callback = cb;
  };
  out$.alert = alert = function(store, text, cb){
    store.current.alert = text;
    return state.callback = cb;
  };
  window.confirmState = state;
}).call(this);
