// Generated by LiveScript 1.6.0
(function(){
  var react, invoiceFuncs, map, receive, getPrimaryInfo, getLang, copiedInform, copy, icons, button, addressHolder, formGroup, addressLink, illQr, send;
  react = require('react');
  invoiceFuncs = require('../invoice-funcs.js');
  map = require('prelude-ls').map;
  receive = require('./receive.js');
  getPrimaryInfo = require('../get-primary-info.js');
  getLang = require('../get-lang.js');
  copiedInform = require('../copied-inform.js');
  copy = require('../copy.js');
  icons = require('../icons.js');
  button = require('../components/button.js');
  addressHolder = require('../components/address-holder.js');
  formGroup = function(title, iconStyle, content){
    var children;
    return react.createElement('div', {
      className: 'form-group'
    }, children = [
      react.createElement('label', {
        style: iconStyle,
        className: 'control-label'
      }, ' ' + title), content()
    ]);
  };
  addressLink = function(store, web3t){
    var wallet;
    if (store.preference.disableInvoice === true) {
      return null;
    }
    wallet = invoiceFuncs(store, web3t).wallet;
    return addressHolder({
      store: store,
      wallet: wallet
    });
  };
  illQr = function(store, web3t){
    var children;
    return react.createElement('div', {
      className: 'ill-qr'
    }, children = [
      react.createElement('img', {
        src: icons.invoiceIllTop + "",
        className: 'ill ill-top'
      }), react.createElement('img', {
        src: icons.invoiceIllMiddle + "",
        className: 'ill ill-middle move'
      }), react.createElement('img', {
        src: icons.invoiceIllDown + "",
        className: 'ill'
      })
    ]);
  };
  send = function(arg$){
    var store, web3t, ref$, wallet, cancel, children;
    store = arg$.store, web3t = arg$.web3t;
    ref$ = invoiceFuncs(store, web3t), wallet = ref$.wallet, cancel = ref$.cancel;
    return react.createElement('div', {
      className: 'content content-1460191937'
    }, children = [
      illQr(store, web3t), addressLink(store, web3t), receive(store, wallet), button({
        store: store,
        text: 'cancel',
        onClick: cancel,
        icon: 'close2'
      })
    ]);
  };
  module.exports = send;
}).call(this);
