// Generated by LiveScript 1.6.0
(function(){
  var react, reactDom, navigate, getPrimaryInfo, web3, getLang, historyFuncs, icon, switchAccount, icons, epoch, videoupload, alertDemo, uploadVideo, uploadVideoProgress, videoList, burger, menu, home, trend, subscr, history, video, videostorage;
  react = require('react');
  reactDom = require('react-dom');
  navigate = require('../navigate.ls');
  getPrimaryInfo = require('../get-primary-info.ls');
  web3 = require('../web3.ls');
  getLang = require('../get-lang.ls');
  historyFuncs = require('../history-funcs.ls');
  icon = require('./icon.ls');
  switchAccount = require('./switch-account.ls');
  icons = require('../icons.ls');
  epoch = require('./epoch.ls');
  videoupload = require('./videoupload.ls');
  alertDemo = require('./alert-demo.ls');
  uploadVideo = require('../components/upload-video.ls');
  uploadVideoProgress = require('../components/upload-video-progress.ls');
  videoList = require('../components/video-list.ls');
  burger = require('../components/burger.ls');
  menu = function(store, web3t){
    var info, dragFile, filterBody, openUploadLink, children;
    info = getPrimaryInfo(store);
    dragFile = function(){
      store.video.drag = !store.video.drag;
      return store.video.menuOpen = !store.video.menuOpen;
    };
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    openUploadLink = function(){
      return store.video.uploadLink = true;
    };
    return react.createElement('div', {
      style: filterBody,
      className: 'menu'
    }, children = react.createElement('div', {
      className: 'middle'
    }, children = [
      false ? react.createElement('div', {
        onClick: openUploadLink,
        className: 'table-row-menu'
      }, children = react.createElement('div', {
        className: 'col folder-menu'
      }, children = react.createElement('span', {}, children = [
        react.createElement('img', {
          src: icons.addVideo + "",
          className: 'icon-svg'
        }), " Upload link"
      ]))) : void 8, react.createElement('div', {
        onClick: dragFile,
        className: 'table-row-menu'
      }, children = react.createElement('div', {
        className: 'col folder-menu'
      }, children = react.createElement('span', {}, children = [
        react.createElement('img', {
          src: icons.addVideo + "",
          className: 'icon-svg'
        }), " Upload video"
      ])))
    ]));
  };
  home = function(store, web3t){
    var lang, goBack, info, switchFiles, fileTree, style, borderStyle, borderRight, borderStyle2, borderStyle3, buttonPrimary2Style, headerTableStyle, dashedBorder, filterBody, borderB, buttonPrimary1Style, inputStyle, lightText, iconStyle, gotoDetails, dragFileClose, children;
    lang = getLang(store);
    goBack = historyFuncs(store, web3t).goBack;
    info = getPrimaryInfo(store);
    switchFiles = function(){
      return store.current.files = !store.current.files;
    };
    fileTree = store.current.files ? 'file-tree' : "";
    style = {
      background: info.app.wallet,
      color: info.app.text
    };
    borderStyle = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    borderStyle2 = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border,
      background: "#4b2888"
    };
    borderStyle3 = {
      color: info.app.text,
      borderBottom: "0"
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    buttonPrimary2Style = {
      border: "1px solid " + info.app.primary2,
      color: info.app.text,
      background: info.app.primary2,
      backgroundColor: info.app.primary2Spare
    };
    headerTableStyle = {
      borderBottom: "1px solid " + info.app.border,
      background: info.app.walletLight,
      position: "sticky"
    };
    dashedBorder = {
      borderColor: info.app.border + "",
      color: info.app.color3
    };
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    borderB = {
      borderBottom: "1px solid " + info.app.border
    };
    buttonPrimary1Style = {
      border: "1px solid " + info.app.primary1,
      color: info.app.text,
      background: info.app.primary1,
      backgroundColor: info.app.primary1Spare
    };
    inputStyle = {
      background: info.app.wallet,
      border: "0",
      color: info.app.text
    };
    lightText = {
      color: info.app.color3
    };
    iconStyle = {
      filter: info.app.nothingIcon
    };
    gotoDetails = function(){
      return navigate(store, web3t, 'videostoragedetails');
    };
    dragFileClose = function(){
      return store.video.drag = !store.video.drag;
    };
    return react.createElement('div', {
      className: fileTree + " panel-content dragarea"
    }, children = [
      uploadVideo({
        store: store
      }), react.createElement('h2', {
        className: 'header'
      }, ' Recommended'), videoList({
        store: store,
        web3t: web3t
      })
    ]);
  };
  trend = function(store, web3t){
    var lang, goBack, info, style, borderStyle, borderRight, borderStyle2, borderStyle3, buttonPrimary2Style, headerTableStyle, dashedBorder, filterBody, borderB, buttonPrimary1Style, inputStyle, lightText, iconStyle, gotoDetails, switchFiles, fileTree, children;
    lang = getLang(store);
    goBack = historyFuncs(store, web3t).goBack;
    info = getPrimaryInfo(store);
    style = {
      background: info.app.wallet,
      color: info.app.text
    };
    borderStyle = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    borderStyle2 = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border,
      background: "#4b2888"
    };
    borderStyle3 = {
      color: info.app.text,
      borderBottom: "0"
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    buttonPrimary2Style = {
      border: "1px solid " + info.app.primary2,
      color: info.app.text,
      background: info.app.primary2,
      backgroundColor: info.app.primary2Spare
    };
    headerTableStyle = {
      borderBottom: "1px solid " + info.app.border,
      background: info.app.walletLight,
      position: "sticky"
    };
    dashedBorder = {
      borderColor: info.app.border + "",
      color: info.app.color3
    };
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    borderB = {
      borderBottom: "1px solid " + info.app.border
    };
    buttonPrimary1Style = {
      border: "1px solid " + info.app.primary1,
      color: info.app.text,
      background: info.app.primary1,
      backgroundColor: info.app.primary1Spare
    };
    inputStyle = {
      background: info.app.wallet,
      border: "0",
      color: info.app.text
    };
    lightText = {
      color: info.app.color3
    };
    iconStyle = {
      filter: info.app.nothingIcon
    };
    gotoDetails = function(){
      return navigate(store, web3t, 'videostoragedetails');
    };
    switchFiles = function(){
      return store.current.files = !store.current.files;
    };
    fileTree = store.current.files ? 'file-tree' : "";
    return react.createElement('div', {
      className: fileTree + " similarvideo"
    }, children = [
      react.createElement('h2', {
        className: 'header'
      }, ' Trending'), react.createElement('div', {
        className: 'section'
      }, children = react.createElement('div', {
        onClick: gotoDetails,
        className: 'source'
      }, children = [
        react.createElement('span', {
          className: 'play'
        }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
          onClick: gotoDetails,
          width: '560',
          height: '315',
          src: 'https://www.youtube.com/embed/2jdA5EwQV9M',
          frameborder: '0',
          allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
          allowfullscreen: ''
        }), react.createElement('span', {
          className: 'content-right'
        }, children = [
          react.createElement('div', {
            className: 'header'
          }, ' How to setup New Velas Web Wallet Tutorial'), react.createElement('ul', {
            className: 'stat'
          }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 122 views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 5 days ago'))]), react.createElement('ul', {
            className: 'stat-text'
          }, children = react.createElement('li', {}, children = react.createElement('span', {}, ' Velas blockchain uses AI-enhanced DPOS (AIDPOS) consensus for high volume transactions processing without sacrificing decentralization and security.')))
        ])
      ])), react.createElement('div', {
        className: 'section'
      }, children = react.createElement('div', {
        onClick: gotoDetails,
        className: 'source'
      }, children = [
        react.createElement('span', {
          className: 'play'
        }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
          onClick: gotoDetails,
          width: '560',
          height: '315',
          src: 'https://www.youtube.com/embed/USGLlp-zfhI',
          frameborder: '0',
          allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
          allowfullscreen: ''
        }), react.createElement('span', {
          className: 'content-right'
        }, children = [
          react.createElement('div', {
            className: 'header'
          }, ' Velas Explainer Video'), react.createElement('ul', {
            className: 'stat'
          }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 1.4K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 8 mounths ago'))]), react.createElement('ul', {
            className: 'stat-text'
          }, children = react.createElement('li', {}, children = react.createElement('span', {}, ' Velas blockchain uses AI-enhanced DPOS (AIDPOS) consensus for high volume transactions processing without sacrificing decentralization and security.')))
        ])
      ]))
    ]);
  };
  subscr = function(store, web3t){
    var lang, goBack, info, switchFiles, fileTree, style, borderStyle, borderRight, borderStyle2, borderStyle3, buttonPrimary2Style, headerTableStyle, dashedBorder, filterBody, borderB, buttonPrimary1Style, inputStyle, lightText, iconStyle, gotoDetails, dragFileClose, headerStyleLight, children;
    lang = getLang(store);
    goBack = historyFuncs(store, web3t).goBack;
    info = getPrimaryInfo(store);
    switchFiles = function(){
      return store.current.files = !store.current.files;
    };
    fileTree = store.current.files ? 'file-tree' : "";
    style = {
      background: info.app.wallet,
      color: info.app.text
    };
    borderStyle = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    borderStyle2 = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border,
      background: "#4b2888"
    };
    borderStyle3 = {
      color: info.app.text,
      borderBottom: "0"
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    buttonPrimary2Style = {
      border: "1px solid " + info.app.primary2,
      color: info.app.text,
      background: info.app.primary2,
      backgroundColor: info.app.primary2Spare
    };
    headerTableStyle = {
      borderBottom: "1px solid " + info.app.border,
      background: info.app.walletLight,
      position: "sticky"
    };
    dashedBorder = {
      borderColor: info.app.border + "",
      color: info.app.color3
    };
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    borderB = {
      borderBottom: "1px solid " + info.app.border
    };
    buttonPrimary1Style = {
      border: "1px solid " + info.app.primary1,
      color: info.app.text,
      background: info.app.primary1,
      backgroundColor: info.app.primary1Spare
    };
    inputStyle = {
      background: info.app.wallet,
      border: "0",
      color: info.app.text
    };
    lightText = {
      color: info.app.color3
    };
    iconStyle = {
      filter: info.app.nothingIcon
    };
    gotoDetails = function(){
      return navigate(store, web3t, 'videostoragedetails');
    };
    dragFileClose = function(){
      return store.video.drag = !store.video.drag;
    };
    headerStyleLight = {
      borderBottom: "1px solid " + info.app.borderLight,
      color: info.app.text
    };
    return react.createElement('div', {
      className: fileTree + " panel-content dragarea subscr"
    }, children = [
      store.video.drag ? react.createElement('div', {
        onClick: dragFileClose,
        className: 'header-table dragfile dragarea'
      }, children = react.createElement('div', {
        style: dashedBorder,
        className: 'cell network'
      }, children = [
        react.createElement('img', {
          src: icons.imgDrag + "",
          style: iconStyle,
          className: 'bounce'
        }), " Drag and Drop here", react.createElement('br', {}), " or", react.createElement('span', {}, ' Browse files')
      ])) : void 8, react.createElement('div', {
        style: headerStyleLight,
        className: 'block-content'
      }, children = [
        react.createElement('h2', {
          className: 'header'
        }, ' Today'), react.createElement('div', {
          className: 'section'
        }, children = react.createElement('div', {
          onClick: gotoDetails,
          className: 'source'
        }, children = [
          react.createElement('span', {
            className: 'play'
          }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
            onClick: gotoDetails,
            width: '560',
            height: '315',
            src: 'https://www.youtube.com/embed/USGLlp-zfhI',
            frameborder: '0',
            allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
            allowfullscreen: ''
          }), react.createElement('div', {
            className: 'title-video'
          }, children = [
            react.createElement('span', {}, children = react.createElement('img', {
              src: info.branding.logo + "",
              className: 'account'
            })), react.createElement('span', {}, children = [
              react.createElement('div', {
                className: 'header'
              }, ' Velas Explainer Video'), react.createElement('ul', {
                className: 'stat'
              }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 2K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 5 days ago'))])
            ])
          ])
        ])), react.createElement('div', {
          className: 'section'
        }, children = react.createElement('div', {
          onClick: gotoDetails,
          className: 'source'
        }, children = [
          react.createElement('span', {
            className: 'play'
          }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
            onClick: gotoDetails,
            width: '560',
            height: '315',
            src: 'https://www.youtube.com/embed/2jdA5EwQV9M',
            frameborder: '0',
            allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
            allowfullscreen: ''
          }), react.createElement('div', {
            className: 'title-video'
          }, children = [
            react.createElement('span', {}, children = react.createElement('img', {
              src: info.branding.logo + "",
              className: 'account'
            })), react.createElement('span', {}, children = [
              react.createElement('div', {
                className: 'header'
              }, ' Velas Explainer Video'), react.createElement('ul', {
                className: 'stat'
              }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 50K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 1 mounth ago'))])
            ])
          ])
        ])), react.createElement('div', {
          className: 'section'
        }, children = react.createElement('div', {
          onClick: gotoDetails,
          className: 'source'
        }, children = [
          react.createElement('span', {
            className: 'play'
          }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
            onClick: gotoDetails,
            width: '560',
            height: '315',
            src: 'https://www.youtube.com/embed/USGLlp-zfhI',
            frameborder: '0',
            allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
            allowfullscreen: ''
          }), react.createElement('div', {
            className: 'title-video'
          }, children = [
            react.createElement('span', {}, children = react.createElement('img', {
              src: info.branding.logo + "",
              className: 'account'
            })), react.createElement('span', {}, children = [
              react.createElement('div', {
                className: 'header'
              }, ' Velas Explainer Video'), react.createElement('ul', {
                className: 'stat'
              }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 2K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 5 days ago'))])
            ])
          ])
        ]))
      ]), react.createElement('div', {
        style: headerStyleLight,
        className: 'block-content'
      }, children = [
        react.createElement('h2', {
          className: 'header'
        }, ' Yesterday'), react.createElement('div', {
          className: 'section'
        }, children = react.createElement('div', {
          onClick: gotoDetails,
          className: 'source'
        }, children = [
          react.createElement('span', {
            className: 'play'
          }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
            onClick: gotoDetails,
            width: '560',
            height: '315',
            src: 'https://www.youtube.com/embed/USGLlp-zfhI',
            frameborder: '0',
            allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
            allowfullscreen: ''
          }), react.createElement('div', {
            className: 'title-video'
          }, children = [
            react.createElement('span', {}, children = react.createElement('img', {
              src: info.branding.logo + "",
              className: 'account'
            })), react.createElement('span', {}, children = [
              react.createElement('div', {
                className: 'header'
              }, ' Velas Explainer Video'), react.createElement('ul', {
                className: 'stat'
              }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 2K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 5 days ago'))])
            ])
          ])
        ])), react.createElement('div', {
          className: 'section'
        }, children = react.createElement('div', {
          onClick: gotoDetails,
          className: 'source'
        }, children = [
          react.createElement('span', {
            className: 'play'
          }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
            onClick: gotoDetails,
            width: '560',
            height: '315',
            src: 'https://www.youtube.com/embed/2jdA5EwQV9M',
            frameborder: '0',
            allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
            allowfullscreen: ''
          }), react.createElement('div', {
            className: 'title-video'
          }, children = [
            react.createElement('span', {}, children = react.createElement('img', {
              src: info.branding.logo + "",
              className: 'account'
            })), react.createElement('span', {}, children = [
              react.createElement('div', {
                className: 'header'
              }, ' Velas Explainer Video'), react.createElement('ul', {
                className: 'stat'
              }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 50K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 1 mounth ago'))])
            ])
          ])
        ]))
      ])
    ]);
  };
  history = function(store, web3t){
    var lang, goBack, info, style, borderStyle, borderRight, borderStyle2, borderStyle3, buttonPrimary2Style, headerTableStyle, dashedBorder, filterBody, borderB, buttonPrimary1Style, inputStyle, lightText, iconStyle, gotoDetails, switchFiles, fileTree, children;
    lang = getLang(store);
    goBack = historyFuncs(store, web3t).goBack;
    info = getPrimaryInfo(store);
    style = {
      background: info.app.wallet,
      color: info.app.text
    };
    borderStyle = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    borderStyle2 = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border,
      background: "#4b2888"
    };
    borderStyle3 = {
      color: info.app.text,
      borderBottom: "0"
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border
    };
    buttonPrimary2Style = {
      border: "1px solid " + info.app.primary2,
      color: info.app.text,
      background: info.app.primary2,
      backgroundColor: info.app.primary2Spare
    };
    headerTableStyle = {
      borderBottom: "1px solid " + info.app.border,
      background: info.app.walletLight,
      position: "sticky"
    };
    dashedBorder = {
      borderColor: info.app.border + "",
      color: info.app.color3
    };
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    borderB = {
      borderBottom: "1px solid " + info.app.border
    };
    buttonPrimary1Style = {
      border: "1px solid " + info.app.primary1,
      color: info.app.text,
      background: info.app.primary1,
      backgroundColor: info.app.primary1Spare
    };
    inputStyle = {
      background: info.app.wallet,
      border: "0",
      color: info.app.text
    };
    lightText = {
      color: info.app.color3
    };
    iconStyle = {
      filter: info.app.nothingIcon
    };
    gotoDetails = function(){
      return navigate(store, web3t, 'videostoragedetails');
    };
    switchFiles = function(){
      return store.current.files = !store.current.files;
    };
    fileTree = store.current.files ? 'file-tree' : "";
    return react.createElement('div', {
      className: fileTree + " similarvideo"
    }, children = [
      react.createElement('h2', {
        className: 'header'
      }, ' Watch history'), react.createElement('h2', {
        className: 'header'
      }, ' Today'), react.createElement('div', {
        className: 'section'
      }, children = react.createElement('div', {
        onClick: gotoDetails,
        className: 'source'
      }, children = [
        react.createElement('span', {
          className: 'play'
        }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
          onClick: gotoDetails,
          width: '560',
          height: '315',
          src: 'https://www.youtube.com/embed/2jdA5EwQV9M',
          frameborder: '0',
          allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
          allowfullscreen: ''
        }), react.createElement('span', {
          className: 'content-right'
        }, children = [
          react.createElement('div', {
            className: 'header'
          }, ' How to setup New Velas Web Wallet Tutorial'), react.createElement('ul', {
            className: 'stat'
          }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 122 views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 5 days ago'))]), react.createElement('ul', {
            className: 'stat-text'
          }, children = react.createElement('li', {}, children = react.createElement('span', {}, ' Velas blockchain uses AI-enhanced DPOS (AIDPOS) consensus for high volume transactions processing without sacrificing decentralization and security.')))
        ])
      ])), react.createElement('div', {
        className: 'section'
      }, children = react.createElement('div', {
        onClick: gotoDetails,
        className: 'source'
      }, children = [
        react.createElement('span', {
          className: 'play'
        }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
          onClick: gotoDetails,
          width: '560',
          height: '315',
          src: 'https://www.youtube.com/embed/USGLlp-zfhI',
          frameborder: '0',
          allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
          allowfullscreen: ''
        }), react.createElement('span', {
          className: 'content-right'
        }, children = [
          react.createElement('div', {
            className: 'header'
          }, ' Velas Explainer Video'), react.createElement('ul', {
            className: 'stat'
          }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 1.4K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 8 mounths ago'))]), react.createElement('ul', {
            className: 'stat-text'
          }, children = react.createElement('li', {}, children = react.createElement('span', {}, ' Velas blockchain uses AI-enhanced DPOS (AIDPOS) consensus for high volume transactions processing without sacrificing decentralization and security.')))
        ])
      ])), react.createElement('h2', {
        className: 'header'
      }, ' Yesterday'), react.createElement('div', {
        className: 'section'
      }, children = react.createElement('div', {
        onClick: gotoDetails,
        className: 'source'
      }, children = [
        react.createElement('span', {
          className: 'play'
        }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
          onClick: gotoDetails,
          width: '560',
          height: '315',
          src: 'https://www.youtube.com/embed/2jdA5EwQV9M',
          frameborder: '0',
          allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
          allowfullscreen: ''
        }), react.createElement('span', {
          className: 'content-right'
        }, children = [
          react.createElement('div', {
            className: 'header'
          }, ' How to setup New Velas Web Wallet Tutorial'), react.createElement('ul', {
            className: 'stat'
          }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 122 views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 5 days ago'))]), react.createElement('ul', {
            className: 'stat-text'
          }, children = react.createElement('li', {}, children = react.createElement('span', {}, ' Velas blockchain uses AI-enhanced DPOS (AIDPOS) consensus for high volume transactions processing without sacrificing decentralization and security.')))
        ])
      ])), react.createElement('div', {
        className: 'section'
      }, children = react.createElement('div', {
        onClick: gotoDetails,
        className: 'source'
      }, children = [
        react.createElement('span', {
          className: 'play'
        }, children = icon('TriangleRight', 15)), react.createElement('iframe', {
          onClick: gotoDetails,
          width: '560',
          height: '315',
          src: 'https://www.youtube.com/embed/USGLlp-zfhI',
          frameborder: '0',
          allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
          allowfullscreen: ''
        }), react.createElement('span', {
          className: 'content-right'
        }, children = [
          react.createElement('div', {
            className: 'header'
          }, ' Velas Explainer Video'), react.createElement('ul', {
            className: 'stat'
          }, children = [react.createElement('li', {}, children = react.createElement('span', {}, ' 1.4K views')), react.createElement('li', {}, children = react.createElement('span', {}, ' 8 mounths ago'))]), react.createElement('ul', {
            className: 'stat-text'
          }, children = react.createElement('li', {}, children = react.createElement('span', {}, ' Velas blockchain uses AI-enhanced DPOS (AIDPOS) consensus for high volume transactions processing without sacrificing decentralization and security.')))
        ])
      ]))
    ]);
  };
  video = function(store, web3t){
    var children;
    return react.createElement('div', {
      className: 'panel-content'
    }, children = react.createElement('p', {
      className: 'results'
    }, ' This tab is under development'));
  };
  videostorage = function(arg$){
    var store, web3t, lang, goBack, gotoSearch, info, filterBody, headerTableStyle, active, switchProgress, hideProgress, switchFiles, fileTree, style, borderStyle, tabsStyle, borderStyle3, borderRight, buttonPrimary2Style, dashedBorder, borderB, buttonPrimary1Style, inputStyle, lightText, iconStyle, activate, activateHome, activateTrend, activateSubscr, activateHistory, activateVideo, activeClass, activeHome, activeTrend, activeSubscr, activeHistory, activeVideo, expandCollapse, showClass, openUploadLink, children;
    store = arg$.store, web3t = arg$.web3t;
    lang = getLang(store);
    goBack = historyFuncs(store, web3t).goBack;
    gotoSearch = function(){
      return navigate(store, web3t, 'search');
    };
    info = getPrimaryInfo(store);
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    headerTableStyle = {
      borderBottom: "1px solid " + info.app.border,
      background: info.app.walletLight,
      position: "sticky"
    };
    active = store.current.active ? 'active' : "";
    switchProgress = function(){
      return store.current.progress = !store.current.progress;
    };
    hideProgress = store.current.progress ? 'hide-progress' : "";
    switchFiles = function(){
      return store.current.files = !store.current.files;
    };
    fileTree = store.current.files ? 'file-tree' : "";
    style = {
      background: info.app.wallet,
      color: info.app.text
    };
    borderStyle = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border,
      background: info.app.background,
      backgroundColor: info.app.bgspare
    };
    tabsStyle = {
      color: info.app.text,
      borderBottom: "1px solid " + info.app.border
    };
    borderStyle3 = {
      color: info.app.text,
      borderBottom: "0"
    };
    borderRight = {
      color: info.app.text,
      borderRight: "1px solid " + info.app.border,
      background: info.app.header
    };
    buttonPrimary2Style = {
      border: "1px solid " + info.app.primary2,
      color: info.app.text,
      background: info.app.primary2,
      backgroundColor: info.app.primary2Spare
    };
    headerTableStyle = {
      borderBottom: "1px solid " + info.app.border,
      background: info.app.walletLight,
      position: "sticky"
    };
    dashedBorder = {
      borderColor: info.app.border + "",
      color: info.app.color3
    };
    filterBody = {
      border: "1px solid " + info.app.border,
      background: info.app.header
    };
    borderB = {
      borderBottom: "1px solid " + info.app.border
    };
    buttonPrimary1Style = {
      border: "1px solid " + info.app.primary1,
      color: info.app.text,
      background: info.app.primary1,
      backgroundColor: info.app.primary1Spare
    };
    inputStyle = {
      background: info.app.wallet,
      border: "0",
      color: info.app.text
    };
    lightText = {
      color: info.app.color3
    };
    iconStyle = {
      filter: info.app.nothingIcon
    };
    activate = function(tab){
      return function(){
        return store.video.tab = tab;
      };
    };
    activateHome = activate('home');
    activateTrend = activate('trend');
    activateSubscr = activate('subscr');
    activateHistory = activate('history');
    activateVideo = activate('video');
    activeClass = function(tab){
      if (store.video.tab === tab) {
        return 'active';
      } else {
        return '';
      }
    };
    activeHome = activeClass('home');
    activeTrend = activeClass('trend');
    activeSubscr = activeClass('subscr');
    activeHistory = activeClass('history');
    activeVideo = activeClass('video');
    expandCollapse = function(){
      return store.video.menuOpen = !store.video.menuOpen;
    };
    showClass = store.current.openMenu ? 'hide' : "";
    openUploadLink = function(){
      return store.video.uploadLink = true;
    };
    return react.createElement('div', {
      className: 'videostorage videostorage-125764082'
    }, children = [
      videoupload({
        store: store,
        web3t: web3t
      }), uploadVideoProgress({
        store: store,
        web3t: web3t
      }), alertDemo(store, web3t), react.createElement('div', {
        style: borderStyle,
        className: 'title'
      }, children = [
        react.createElement('div', {
          className: showClass + " header"
        }, ' Video storage'), react.createElement('div', {
          onClick: gotoSearch,
          className: 'close'
        }, children = react.createElement('img', {
          src: icons.arrowLeft + "",
          className: 'icon-svg'
        })), burger(store, web3t), epoch(store, web3t), switchAccount(store, web3t)
      ]), store.video.menuOpen ? menu(store, web3t) : void 8, react.createElement('div', {
        className: 'search-input'
      }, children = react.createElement('div', {
        style: borderStyle,
        className: 'section'
      }, children = [
        react.createElement('span', {
          onClick: switchFiles,
          className: 'close'
        }, children = react.createElement('img', {
          src: icons.menu + "",
          className: 'icon-svg-video'
        })), react.createElement('span', {
          onClick: expandCollapse,
          className: 'add'
        }, children = react.createElement('img', {
          src: icons.video + "",
          className: 'icon-svg-video'
        })), react.createElement('div', {
          className: 'title'
        }, children = react.createElement('h2', {
          className: 'iron'
        }, children = [
          react.createElement('span', {
            className: 'logo'
          }, children = icon('TriangleRight', 10)), react.createElement('span', {}, ' Vortex')
        ])), react.createElement('div', {
          className: 'description search-field'
        }, children = react.createElement('div', {
          className: 'left'
        }, children = [
          react.createElement('input', {
            type: 'text',
            style: inputStyle,
            value: "velas",
            placeholder: "velas"
          }), react.createElement('div', {
            className: 'icon'
          }, children = icon('Search', 15))
        ]))
      ])), react.createElement('div', {
        className: 'wrapper'
      }, children = [
        react.createElement('div', {
          className: fileTree + " menu-content"
        }, children = react.createElement('div', {
          style: borderRight,
          className: 'section filter'
        }, children = react.createElement('div', {
          className: 'tabs'
        }, children = [
          react.createElement('ul', {
            style: tabsStyle
          }, children = [
            react.createElement('li', {
              onClick: activateHome,
              className: activeHome + ""
            }, children = react.createElement('span', {
              className: 'icon'
            }, children = [
              react.createElement('img', {
                src: icons.home + "",
                className: 'icon-svg-menu'
              }), " Home"
            ])), react.createElement('li', {
              onClick: activateTrend,
              className: activeTrend + ""
            }, children = react.createElement('span', {
              className: 'icon'
            }, children = [
              react.createElement('img', {
                src: icons.flame + "",
                className: 'icon-svg-menu'
              }), " Trending"
            ])), react.createElement('li', {
              onClick: activateSubscr,
              className: activeSubscr + ""
            }, children = react.createElement('span', {
              className: 'icon'
            }, children = [
              react.createElement('img', {
                src: icons.subscriptions + "",
                className: 'icon-svg-menu'
              }), "   Subscriptions"
            ]))
          ]), react.createElement('ul', {
            style: tabsStyle
          }, children = [
            react.createElement('li', {
              onClick: activateHistory,
              className: activeHistory + ""
            }, children = react.createElement('span', {
              className: 'icon'
            }, children = [
              react.createElement('img', {
                src: icons.history + "",
                className: 'icon-svg-menu'
              }), " History"
            ])), react.createElement('li', {
              onClick: activateVideo,
              className: activeVideo + ""
            }, children = react.createElement('span', {
              className: 'icon'
            }, children = [
              react.createElement('img', {
                src: icons.uVideo + "",
                className: 'icon-svg-menu'
              }), " Your videos"
            ]))
          ])
        ]))), activeHome === 'active' ? home(store, web3t) : void 8, activeTrend === 'active' ? trend(store, web3t) : void 8, activeSubscr === 'active' ? subscr(store, web3t) : void 8, activeHistory === 'active' ? history(store, web3t) : void 8, activeVideo === 'active' ? video(store, web3t) : void 8
      ])
    ]);
  };
  module.exports = videostorage;
}).call(this);
