// Generated by LiveScript 1.6.0
(function(){
  var velasWeb3, addresses, abis;
  velasWeb3 = require('./velas-web3.ls');
  addresses = require('./addresses.ls');
  abis = {
    Staking: require("./contracts/StakingAuRa.json").abi,
    ValidatorSet: require("./contracts/ValidatorSetAuRa.json").abi,
    BlockReward: require("./contracts/BlockRewardAuRa.json").abi,
    Development: require("./contracts/VelasDevelopment.json").abi
  };
  module.exports = function(store){
    var web3, api;
    web3 = velasWeb3(store);
    api = {
      Staking: web3.eth.contract(abis.Staking).at(addresses.Staking),
      ValidatorSet: web3.eth.contract(abis.ValidatorSet).at(addresses.ValidatorSet),
      BlockReward: web3.eth.contract(abis.BlockReward).at(addresses.BlockReward),
      Development: web3.eth.contract(abis.Development).at(addresses.Development),
      web3: web3.eth
    };
    return api;
  };
}).call(this);
