module.exports = 
    add-coin: "동전 추가"
    edit-wallet: "편집하다"
    edit-coins: "동전 편집"
    confirmation : "확인"
    plugin-registry : "플러그인 레지스트리"
    search: "검색"
    confirm: "확인"
    cancel: "취소"
    send: "보내다"
    send-from: "발신"
    recipient: "받는 사람"
    amount: "양"
    use-max: "최대 사용"
    pending: "대기 중"
    invoice-header: "이메일로 송장 보내기"
    funding-address: "자금 주소"
    recipient-email: "이메일 수령인"
    wrong-pin-trials: "잘못된 PIN입니다. 시험판"
    wrong-pin-should: "PIN은 4 자리 여야합니다"
    setup: "설정"
    pin-info : "이 PIN을 기억하여 제 3 자에게 제공하지 마십시오"
    setup-pin : "Setup PIN"
    enter-pin: "PIN을 입력하십시오"
    secret-phrase: "비밀 문구"
    secret-phrase-warning: "이 문구를 안전하게 보관할 책임은 귀하에게 있습니다. 이 문구를 잃어버린 경우 복원 할 수 없습니다."
    secret-phrase-change: "이것을 편집하면 기존 지갑이 사라지고 모든 동전이 손실됩니다."
    save: "저장"
    edit-phrase: "비밀 편집"
    your-nickname: "닉네임"
    your-nickname-info: "당신은 당신의 계정에 별명, 이메일 또는 전화 번호를 첨��하고 친구들과 공유 할 수 있습니다. 그들은 당신의 암호를 해결하기 위해 당신의 닉을 사용합니다"
    switch-account-index: "계정 인덱스 전환"
    for-advanced-users: "고급 사용자 만"
    switch-account-info: "계정 색인을 전환하여 고유 한 주소를 많이 가질 수 있습니다. 기본적으로 인덱스는 1이지만 0-2,147,483,647 범위에서 변경할 수 있습니다."
    export-private-key: "개인 키 내보내기"
    export-private-key-warning: "이 조치의 정확한 이유를 이해하지 못하고 위험을 감수하지 않는 경우에는 절대로 수행하지 마십시오."
    show-secret: "비밀 표시"
    total-balance: "전체 균형"
    verify-nickname: "닉네임 확인"
    get-nickname: "닉네임 받기"
    register: "레지스터"
    new-seed-phrase: "새로운 씨구"
    new-seed-placeholder: "비밀 12 단어 문구를 입력하십시오"
    generate: "일으키다"
    new-seed-warning: "문구는 컴퓨터에 안전하게 저장됩니다. 타사에 양도하지 말고 사본을 안전한 곳에 보관하십시오"
    invoice : "송장"
    receive: "받다"
    history: "역사"
    seed-warning: "시드 문구에서 잔액이 0이 될 수있는 문제가 있습니다. 이 버튼을 클릭하면 서식 문제를 해결할 수 있습니���"
    topup: "충전"
    fix-issue: "문제 해결"
    you-spend: "너는 쓴다"
    recipient-obtains: "받는 사람"
    transaction-fee: "거래 수수료"
    auto: "자동"
    cheap: "싼"
    your: "너의"
    transaction: "트랜잭션"
    has-been-sent: "전송 된"
    home: "집"
    terms: "이용 약관에 동의하십시오"
    accept: "동의하기"
    price: "가격"
    balance: "균형"
    open: "열다"
    account-index: "계정 인덱스"
    settings: "설정"
    lock: "자물쇠"
    edit-secret: "비밀 편집"
    your-transactions: "거래"
    nothing-to-show: "여기는 볼게 없다!"
    make-tx: "첫 거래를하거나 필터를 변경하십시오."
    fee: "회비"
    delete: "지우다"
    created: "만들어진"
    manage-account: "계정 관리"
    copied: "클립 보드에 복사했습니다!"
    private-key-enter-pin: "PIN 코드를 입력하십시오"
    private-key-enter-coin: "동전을 입력하십시오. 예 : BTC, ETH, GBX"
    phrase-safe-place: "이 문구를 안전한 곳에 보관했는지 확인하십시오."
    your-wallets: "지갑"
    verify-seed-phrase: "시드 문구 확인"
    phrase-word: "시드 문구의 네 번째 단어를 입력하십시오"
    placeholder-phrase-word: "네 번째 단어를 입력하십시오"
    confirm-seed: "종자 확인"
    welcome-wallet: "어서 오십시오!"
    cta: "아래에서 작업을 선택하십시오"
    new-wallet: "새 월렛 만들기"
    restore-wallet: "기존 월렛 복원"
    words-are-not-match: "단어가 일치하지 않습니다"
    back: "뒤"
    your-language: "당신의 언어"
    links-doc: "연결"
    privacy-policy: "개인 정보 정책"
    terms-of-use: "이용 약관"
    read: "더 읽어보기"
    version: "버전"
    about-wallet: "하나의 니모닉 문구로 관리되는 다중 통화 월렛"
    pls-read: "우리를 읽으십시오 "