#!/bin/sh
BRANCH=`git rev-parse --abbrev-ref HEAD`

echo "RUNNING PRE PUSH $BRANCH"
if [ "$BRANCH" = "master" ]; then
  echo RUNNING PRE PUSH ON MASTER
  TARGET="./package.json"
  if [ ! -f "$TARGET" ]; then
     echo "missing file $TARGET"
     exit 1;
  fi

  LINE=$(grep -o ${TARGET} -e '\"version\": \"[0-9\.]*\"');
  declare -a LINE;


  LINE=(`echo $LINE | tr ":" " "`);

  VERSION=(${LINE[1]//'"'/$''});

  LINE=(`git tag -l | grep v${VERSION}`)
  if [-z "$LINE"]; then
    echo RUNNING PRE PUSH ON MASTER WITHOUT TAG v${VERSION}
    git tag -a v${VERSION} -m "Autocreated tag from version ${VERSION}"

    git push --tags
  fi
fi
