// Generated by LiveScript 1.6.0
(function(){
  var addCommas;
  addCommas = function(x){
    var pattern;
    x = x.toString();
    pattern = /(-?\d+)(\d{3})/;
    while (pattern.test(x)) {
      x = x.replace(pattern, "$1,$2");
    }
    return x;
  };
  module.exports = function(value){
    var ref$, head, dec, firstHead;
    if (value == null) {
      return '..';
    }
    if (value === '..') {
      return '..';
    }
    ref$ = value.toString().split('.'), head = ref$[0], dec = ref$[1];
    firstHead = addCommas(head);
    if ((dec != null ? dec : "").length === 0) {
      return firstHead + ".00";
    }
    return firstHead + "." + dec.substr(0, 4);
  };
}).call(this);
